encoding: utf-8
#safe: true

# Author Settings

baseurl: /baibingqianlan.github.io
destination: ./baibingqianlan.github.io
author: 百冰千岚 # add your name
author-img: Baibingqianlan.jpg # add your photo
top-img: top1.jpg # top-img
top-des: 山水风景，一瓢何求
about-author: I am a C++/Python developer focusing on simulation development. Always hungry to keep learning. # add description
email: 444129199@qq.com # add your Email address

plugins: [jekyll-paginate, jekyll-sitemap, jekyll-feed]

paginate: 5
paginate_path: "/page:num"

intensedebate_comments: true
